name: XiaoBind
main: zbv5.cn.XiaoBind.Main
version: 1.1.1
api: 1.0.0
author: 逍遥
permissions:
  XiaoBind.command:
    description: 使用默认指令所需权限
    default: true
  XiaoBind.Bind:
    description: 使用 /Bind 指令所需权限
    default: op
  XiaoBind.Bind.Other:
    description: 使用 /Bind <player> 指令所需权限
    default: op
  XiaoBind.BindOnEquip:
    description: 使用 /BindOnEquip 指令所需权限
    default: op
  XiaoBind.BindOnEquip.Other:
    description: 使用 /BindOnEquip <player> 指令所需权限
    default: op
  XiaoBind.BindOnPickup:
    description: 使用 /BindOnPickup 指令所需权限
    default: op
  XiaoBind.BindOnPickup.Other:
    description: 使用 /BindOnPickup <player> 指令所需权限
    default: op
  XiaoBind.BindOnUse:
    description: 使用 /BindOnUse 指令所需权限
    default: op
  XiaoBind.BindOnUse.Other:
    description: 使用 /BindOnUse <player> 指令所需权限
    default: op
  XiaoBind.UnBind:
    description: 使用 /UnBind 指令所需权限
    default: op
  XiaoBind.UnBind.Other:
    description: 使用 /UnBind <player> 指令所需权限
    default: op
  XiaoBind.ignore:
    description: 无视丢弃/点击/手持等限制所需权限
    default: op
  XiaoBind.tags:
    description: 使用指令查询当前Tags
    default: op
  XiaoBind.claim:
    description: 打开领取绑定物品页面所需权限
    default: true
  XiaoBind.use:
    description: 打开物品使用页面所需权限
    default: true
  XiaoBind.search:
    description: 搜寻玩家背包所需权限
    default: op
  XiaoBind.give:
    description: 给予玩家物品所需权限
    default: op
  XiaoBind.admin:
    description: 打开管理页面所需权限
    default: op
  XiaoBind.reload:
    description: 重载配置文件所需权限
    default: op